import jsPDF from 'jspdf';
import type {
  FetchOverviewLaunchesParams,
  OverviewLaunchApiRow,
  OverviewLaunchesProjectOption,
  OverviewLaunchesResponse,
  OverviewWidgetsResponse,
} from './overviewWidgetsApi';
import {
  toCsv,
  downloadBlob,
  waitForElementsToRender,
  captureElementAsPaginatedImage,
} from './exportHelpers';
import { overviewCategoryLabelForRepos } from '../constants/overviewCategories';

export type OverviewExportFormat = 'pdf' | 'csv';

export type OverviewExportTab = 'widgets' | 'launches';

interface CommonFilters {
  gitlabProjectNames?: string[];
  projectIds?: number[];
  projectOptions?: OverviewLaunchesProjectOption[];
}

export interface OverviewWidgetsExportInput {
  format: OverviewExportFormat;
  /** Selector for the DOM element to screenshot in PDF mode. */
  domSelector: string;
  /** In-memory data used for CSV export. */
  data: OverviewWidgetsResponse;
  filters: CommonFilters;
}

export interface OverviewLaunchesExportInput {
  format: OverviewExportFormat;
  domSelector: string;
  filters: CommonFilters & {
    startFrom: string | null;
    startTo: string | null;
    executionFilter: 'all' | 'me' | 'cron';
    statusFilter: 'passed' | 'failed' | null;
    defectTagFilter: string | null;
    hasIssuesFilter: boolean;
  };
  fetchAllLaunches: (base: FetchOverviewLaunchesParams) => Promise<OverviewLaunchesResponse>;
  fetchParamsBase: FetchOverviewLaunchesParams;
}

const MAX_LAUNCH_PAGES = 10;
const LAUNCH_EXPORT_PER_PAGE = 100;
const A4_PORTRAIT_CONTENT_WIDTH = 180;
const A4_TOP_MARGIN = 15;

function todayIsoDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function projectNamesFromIds(
  ids: number[] | undefined,
  options: OverviewLaunchesProjectOption[] | undefined,
): string {
  if (!ids || ids.length === 0) return '';
  if (!options || options.length === 0) return ids.join(', ');
  const byId = new Map(options.map(o => [o.id, o.name || `#${o.id}`]));
  return ids.map(id => byId.get(id) ?? `#${id}`).join(', ');
}

function filterSummaryLines(input: OverviewLaunchesExportInput | OverviewWidgetsExportInput): string[] {
  const lines: string[] = [];
  const { filters } = input;
  if (filters.gitlabProjectNames && filters.gitlabProjectNames.length > 0) {
    const label = overviewCategoryLabelForRepos(filters.gitlabProjectNames);
    if (label) lines.push(`Repository: ${label}`);
  }
  const projectsLabel = projectNamesFromIds(filters.projectIds, filters.projectOptions);
  if (projectsLabel !== '') lines.push(`Projects: ${projectsLabel}`);
  if ('startFrom' in filters) {
    if (filters.startFrom || filters.startTo) {
      lines.push(`Start time: ${filters.startFrom ?? '...'} to ${filters.startTo ?? '...'}`);
    }
    if (filters.executionFilter !== 'all') lines.push(`Executed by: ${filters.executionFilter}`);
    if (filters.statusFilter) lines.push(`Status: ${filters.statusFilter}`);
    if (filters.defectTagFilter) lines.push(`Defect tag: ${filters.defectTagFilter}`);
    if (filters.hasIssuesFilter) lines.push('Has issues: yes');
  }
  return lines;
}

function drawPdfHeader(pdf: jsPDF, title: string, subtitle: string, filterLines: string[]): number {
  pdf.setFontSize(20);
  pdf.setTextColor(6, 182, 212);
  pdf.text(title, 15, 18);
  pdf.setFontSize(10);
  pdf.setTextColor(31, 41, 59);
  pdf.text(subtitle, 15, 25);
  pdf.setFontSize(8);
  pdf.setTextColor(107, 114, 128);
  pdf.text(`Generated ${new Date().toLocaleString()}`, 15, 30);

  let y = 36;
  if (filterLines.length > 0) {
    pdf.setFontSize(9);
    pdf.setTextColor(51, 65, 85);
    pdf.text('Filters', 15, y);
    y += 4;
    pdf.setFontSize(8);
    pdf.setTextColor(71, 85, 105);
    for (const line of filterLines) {
      pdf.text(`- ${line}`, 17, y);
      y += 4;
    }
    y += 2;
  }
  return y;
}

function drawPdfFooter(pdf: jsPDF): void {
  const pageCount = pdf.getNumberOfPages();
  pdf.setFontSize(7);
  pdf.setTextColor(107, 114, 128);
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.text(`Generated by SMARTQA on ${new Date().toLocaleString()}`, 15, 290);
    pdf.text(`Page ${i} of ${pageCount}`, 175, 290);
  }
}

async function screenshotTabToPdf(
  input: OverviewLaunchesExportInput | OverviewWidgetsExportInput,
  title: string,
  subtitle: string,
  filenameStem: string,
): Promise<void> {
  const element = document.querySelector(input.domSelector) as HTMLElement | null;
  if (!element) {
    throw new Error('Overview panel not found on the page. Scroll it into view and try again.');
  }

  await waitForElementsToRender();

  const pdf = new jsPDF('p', 'mm', 'a4');
  const headerBottom = drawPdfHeader(pdf, title, subtitle, filterSummaryLines(input));

  await captureElementAsPaginatedImage(element, pdf, {
    x: 15,
    startY: headerBottom + 2,
    contentWidth: A4_PORTRAIT_CONTENT_WIDTH,
    topMargin: A4_TOP_MARGIN,
    bottomMargin: 18,
  });

  drawPdfFooter(pdf);
  pdf.save(`${filenameStem}-${todayIsoDate()}.pdf`);
}

// ---------------------------------------------------------------------------
// Widgets
// ---------------------------------------------------------------------------

function exportWidgetsCsv(input: OverviewWidgetsExportInput): void {
  const { data } = input;
  const rows: (string | number)[][] = [];
  rows.push(['Overview – Widgets']);
  rows.push(['Window from', data.window.from]);
  rows.push(['Window to', data.window.to]);
  rows.push(['Window days', data.window.days]);
  rows.push(['Generated', new Date().toISOString()]);
  for (const line of filterSummaryLines(input)) rows.push([line]);
  rows.push([]);
  rows.push(['=== WEEKLY TOTALS ===']);
  rows.push(['Pass', 'Fail', 'Pass rate %']);
  rows.push([
    data.weeklyTotals.pass,
    data.weeklyTotals.fail,
    data.weeklyTotals.passRate != null ? data.weeklyTotals.passRate.toFixed(2) : '',
  ]);
  rows.push([]);
  rows.push(['=== DEFECT MIX ===']);
  rows.push(['Tag', 'Label', 'Fail count', 'Percent %']);
  for (const m of data.defectMix) {
    rows.push([m.tag, m.label, m.failCount, m.percent != null ? m.percent.toFixed(2) : '']);
  }
  rows.push([]);
  rows.push(['=== EXECUTION BY SERVICE ===']);
  rows.push(['Key', 'Label', 'Pass', 'Fail', 'Pass rate %', 'Band']);
  for (const r of data.executionByService) {
    rows.push([r.key, r.label, r.pass, r.fail, r.passRate != null ? r.passRate.toFixed(2) : '', r.band]);
  }
  rows.push([]);
  rows.push(['=== EXECUTION BY COUNTRY ===']);
  rows.push(['Key', 'Label', 'Pass', 'Fail', 'Pass rate %', 'Band']);
  for (const r of data.executionByCountry) {
    rows.push([r.key, r.label, r.pass, r.fail, r.passRate != null ? r.passRate.toFixed(2) : '', r.band]);
  }
  downloadBlob(new Blob([toCsv(rows)], { type: 'text/csv;charset=utf-8;' }), `overview-widgets-${todayIsoDate()}.csv`);
}

function formatWindowDate(iso: string | undefined): string {
  if (!iso) return '';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
}

export async function exportOverviewWidgets(input: OverviewWidgetsExportInput): Promise<void> {
  if (input.format === 'pdf') {
    const from = formatWindowDate(input.data.window.from);
    const to = formatWindowDate(input.data.window.to);
    const days = input.data.window.days;
    const subtitle = `Window ${from} to ${to} (${days} days)`;
    await screenshotTabToPdf(input, 'Overview', subtitle, 'overview-widgets');
    return;
  }
  exportWidgetsCsv(input);
}

// ---------------------------------------------------------------------------
// Launches
// ---------------------------------------------------------------------------

async function fetchAllLaunchPages(
  input: OverviewLaunchesExportInput,
): Promise<{ launches: OverviewLaunchApiRow[]; truncated: boolean; total: number }> {
  const collected: OverviewLaunchApiRow[] = [];
  let truncated = false;
  let total = 0;
  for (let page = 1; page <= MAX_LAUNCH_PAGES; page++) {
    const res = await input.fetchAllLaunches({
      ...input.fetchParamsBase,
      page,
      perPage: LAUNCH_EXPORT_PER_PAGE,
    });
    collected.push(...res.launches);
    total = res.meta.total;
    if (page >= res.meta.lastPage) return { launches: collected, truncated: false, total };
    if (page === MAX_LAUNCH_PAGES && page < res.meta.lastPage) truncated = true;
  }
  return { launches: collected, truncated, total };
}

const LAUNCH_CSV_COLUMNS: Array<{ key: keyof OverviewLaunchApiRow | 'startTime'; label: string }> = [
  { key: 'testRunExecutionId', label: 'ID' },
  { key: 'displayName', label: 'Name' },
  { key: 'startTime', label: 'Start' },
  { key: 'runnedByLabel', label: 'Ran by' },
  { key: 'source', label: 'Source' },
  { key: 'durationLabel', label: 'Duration' },
  { key: 'total', label: 'Total' },
  { key: 'passed', label: 'Passed' },
  { key: 'failed', label: 'Failed' },
  { key: 'skipped', label: 'Skipped' },
  { key: 'productBug', label: 'Product bug' },
  { key: 'autoBug', label: 'Auto bug' },
  { key: 'systemIssue', label: 'System issue' },
  { key: 'toInvestigate', label: 'To investigate' },
];

function launchCell(row: OverviewLaunchApiRow, key: (typeof LAUNCH_CSV_COLUMNS)[number]['key']): string | number {
  if (key === 'startTime') {
    return row.startTimeRaw ?? row.startTimeDisplay ?? row.startTimeRelative ?? '';
  }
  const value = row[key as keyof OverviewLaunchApiRow];
  if (value == null) return '';
  return typeof value === 'number' ? value : String(value);
}

async function exportLaunchesCsv(input: OverviewLaunchesExportInput): Promise<void> {
  const { launches, truncated, total } = await fetchAllLaunchPages(input);
  if (launches.length === 0) {
    throw new Error('No launches match the current filters.');
  }
  const rows: (string | number)[][] = [];
  rows.push(['Overview – Launches']);
  rows.push(['Generated', new Date().toISOString()]);
  rows.push(['Rows exported', launches.length]);
  rows.push(['Total matching launches', total]);
  if (truncated) rows.push(['Note', `Export capped at ${launches.length} rows.`]);
  for (const line of filterSummaryLines(input)) rows.push([line]);
  rows.push([]);
  rows.push(LAUNCH_CSV_COLUMNS.map(c => c.label));
  for (const row of launches) {
    rows.push(LAUNCH_CSV_COLUMNS.map(c => launchCell(row, c.key)));
  }
  downloadBlob(new Blob([toCsv(rows)], { type: 'text/csv;charset=utf-8;' }), `overview-launches-${todayIsoDate()}.csv`);
}

export async function exportOverviewLaunches(input: OverviewLaunchesExportInput): Promise<void> {
  if (input.format === 'pdf') {
    await screenshotTabToPdf(input, 'Overview', 'Launches snapshot', 'overview-launches');
    return;
  }
  await exportLaunchesCsv(input);
}

export type OverviewExporter = (format: OverviewExportFormat) => Promise<void>;
